### ISSUE TITLE
iOS pod error

### ISSUE THREAD

**Issue by LoganRaja** [flopshot/ReactNative_WhiteLabelDemo#4]

**Comment by LoganRaja** [comment]
Unable to find a target named `WhiteLabelDemo` in project `WhiteLabelDemo.xcodeproj`, did find `PurpleParrots`, `WhiteLabelDemoTests`, `WhiteLabelDemo-tvOS`, `WhiteLabelDemo-tvOSTests`, and `GreenMonkeys`.

**Comment by LoganRaja** [comment]
Unable to find a target named `WhiteLabelDemo` in project `WhiteLabelDemo.xcodeproj`, did find `PurpleParrots`, `WhiteLabelDemoTests`, `WhiteLabelDemo-tvOS`, `WhiteLabelDemo-tvOSTests`, and `GreenMonkeys`.

**Comment by prancky** [comment]
did you find any solution for this?

**Comment by giorgioff** [comment]
same issue here, @LoganRaja, @prancky   do you have any solutions for this? thanks!

**Comment by giorgioff** [comment]
> same issue here, @LoganRaja, @prancky do you have any solutions for this? thanks!

I resolved in this way

```
abstract_target 'AbstractTarget' do
...
...
   target "WLApp1"
   target "WLApp1"
end
```
